### PR TITLE
Recompile inotifywait.exe; test w/ Elixir 1.18

### LINKED ISSUE #102: FileSystem process prevents script from exiting
This started happening for me in Github actions (Windows 10) and locally (Windows 11) after update to Elixir 1.18.

**How to reproduce:**

Environment:
* Windows 10 or 11
* Elixir 1.18
* OTP 27.2

```
# a.exs
{:ok, pid} = FileSystem.start_link(dirs: [Path.expand("~/")])
IO.inspect(pid)
```

Run `mix run a.exs`

**Expected:**
Script prints out the process PID and exits.

**Observed:**
Script prints out the process PID but then stalls and never exits.

### PR DESCRIPTION
**Pull request by dtcaciuc**
Recently updated version does not match the bundled sources and probably came from the upstream, which currently doesn't watch for closed STDIN which Port needs to cleanly shut down the process.

Recompile bundled sources that do have the feature and update the binary.

Fixes #102

### CODE REVIEW

File: test/file_system_test.exs [hunk 1]
```diff
@@ -4,8 +4,9 @@ defmodule FileSystemTest do
   @moduletag os_linux: true, os_macos: true, os_windows: true
 
   test "file event api" do
-    tmp_dir = System.cmd("mktemp", ["-d"]) |> elem(0) |> String.trim()
```
Comment (dtcaciuc) [inline test/file_system_test.exs:7]: AFAIK this command does not normally come with Windows and was absent on my machine.

I borrowed this mktemp_d implementation from the internets and it's not bulletproof but should be good enough for our purposes.

**Comment by falood** [comment]
the CI passed, then let's merge it and I'll bump a version, thanks ♥️
